### ISSUE TITLE
fail to load in Scid and scid vs pc gui

### ISSUE THREAD

**Issue by al75an** [Sopel97/FatTitz#5]
Hi Sopel,
Thank you very much for FatTitz!!
FatTitz fails to load in Scid and scid vs pc gui (Engine Error file not executable or not uci engine)

**Comment by whelanh** [comment]
I believe the reason it doesn't load on Scid is because the net (fat_titz.nnue) is not embedded in the executable.  For some reason this causes a problem with Scid (but not Nibbler, for example). If you compile the executable yourself you can change line 110 in the Makefile to "embed = yes".  Then the resulting executable will run fine in Scid (this is what the pre-compiled Stockfish executables do).

**Comment by Sopel97** [comment]
Yes, the network must be in the working directory of the engine. Some GUIs might not set it up correctly, and then the network cannot be found. A possible workaround would be to put the network file in the SCID directory.

**Comment by al75an** [comment]
Hi,
the nnue file is in same folder with the engine and the error still exist

**Comment by al75an** [comment]
Thank you Sopel,
putting the network file in the SCID directory instead of the engine directory worked

**Comment by Sopel97** [comment]
are you on linux? perhaps the file doesn't have executable rights
